/* 言語ループ 学習データ
 * データ駆動: 対象言語は tr[lang] を追加すれば増やせる。初回は en のみ充填。
 * すべて口語（話し言葉）寄りで登録。
 */

/* ============ 語彙 words ============
 * id / jp(意味) / pos / cat(カテゴリ) / tr{ en:{w:訳, note?} }
 * content=true の語を例文・シャドーイングの対象にする。
 */
window.WORDS = [
  // --- 主語 ---（skip:true = 毎日の新規学習からは除外。まとめには表示）
  { id:"i",    jp:"私",     pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"I" } } },
  { id:"you",  jp:"あなた", pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"you" } } },
  { id:"he",   jp:"彼",     pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"he" } } },
  { id:"she",  jp:"彼女",   pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"she" } } },
  { id:"we",   jp:"私たち", pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"we" } } },
  { id:"this", jp:"これ",   pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"this" } } },
  { id:"that", jp:"それ",   pos:"代名詞", cat:"主語", content:false, skip:true, tr:{ en:{ w:"that" } } },
  { id:"my",   jp:"私の",   pos:"所有格", cat:"主語", content:false, skip:true, tr:{ en:{ w:"my" } } },
  { id:"your", jp:"あなたの", pos:"所有格", cat:"主語", content:false, skip:true, tr:{ en:{ w:"your" } } },
  { id:"his",  jp:"彼の",   pos:"所有格", cat:"主語", content:false, skip:true, tr:{ en:{ w:"his" } } },
  { id:"her",  jp:"彼女の", pos:"所有格", cat:"主語", content:false, skip:true, tr:{ en:{ w:"her" } } },
  { id:"our",  jp:"私たちの", pos:"所有格", cat:"主語", content:false, skip:true, tr:{ en:{ w:"our" } } },

  // --- 動詞 ---
  { id:"go",       jp:"行く",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"go" } } },
  { id:"come",     jp:"来る",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"come" } } },
  { id:"live",     jp:"住む",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"live" } } },
  { id:"eat",      jp:"食べる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"eat" } } },
  { id:"buy",      jp:"買う",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"buy" } } },
  { id:"see",      jp:"見える", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"see" } } },
  { id:"use",      jp:"使う",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"use" } } },
  { id:"hear",     jp:"聞こえる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"hear" } } },
  { id:"wake",     jp:"起きる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"wake up" } } },
  { id:"sleep",    jp:"寝る",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"sleep" } } },
  { id:"speak",    jp:"話す",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"speak" } } },
  { id:"say",      jp:"言う",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"say" } } },
  { id:"talk",     jp:"話をする", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"talk" } } },
  { id:"work",     jp:"働く",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"work" } } },
  { id:"know",     jp:"知っている", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"know" } } },
  { id:"meet",     jp:"会う",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"meet" } } },
  { id:"wait",     jp:"待つ",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"wait" } } },
  { id:"write",    jp:"書く",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"write" } } },
  { id:"have",     jp:"持っている", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"have" } } },
  { id:"start",    jp:"始まる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"start", note:"begin" } } },
  { id:"finish",   jp:"終わる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"finish", note:"end" } } },
  { id:"think",    jp:"思う",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"think" } } },
  { id:"send",     jp:"送る",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"send" } } },
  { id:"be",       jp:"〜です", pos:"動詞", cat:"動詞", content:false, tr:{ en:{ w:"be", note:"am/is/are" } } },
  { id:"understand",jp:"わかる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"understand", note:"get it" } } },
  { id:"read",     jp:"読む",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"read" } } },
  { id:"help",     jp:"助ける", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"help" } } },
  { id:"like",     jp:"好きだ", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"like" } } },
  { id:"enter",    jp:"入る",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"go in", note:"enter" } } },
  { id:"arrive",   jp:"着く",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"arrive", note:"get to" } } },
  { id:"remember", jp:"覚える", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"remember" } } },
  { id:"quit",     jp:"やめる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"quit", note:"stop" } } },
  { id:"become",   jp:"〜になる", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"become" } } },
  { id:"study",    jp:"勉強する", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"study" } } },
  { id:"ride",     jp:"（乗り物に）乗る", pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"take", note:"ride" } } },
  { id:"go_home",  jp:"帰る",   pos:"動詞", cat:"動詞", content:true, tr:{ en:{ w:"go home", note:"go back" } } },

  // --- 形容詞（追加4） ---
  { id:"happy",    jp:"嬉しい",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"happy", note:"glad" } } },
  { id:"favorite", jp:"お気に入りの", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"favorite" } } },
  { id:"foreign",  jp:"外国の",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"foreign" } } },
  { id:"smart",    jp:"賢い",     pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"smart", note:"clever" } } },

  // --- 名詞 ---
  { id:"japan",    jp:"日本",   pos:"名詞", cat:"名詞", content:false, tr:{ en:{ w:"Japan" } } },
  { id:"japanese", jp:"日本人", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"Japanese" } } },
  { id:"morning",  jp:"朝",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"morning" } } },
  { id:"night",    jp:"夜",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"night" } } },
  { id:"friend",   jp:"友達",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"friend" } } },
  { id:"home",     jp:"家",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"home", note:"house" } } },
  { id:"culture",  jp:"文化",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"culture" } } },
  { id:"car",      jp:"車",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"car" } } },
  { id:"food",     jp:"食べ物", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"food" } } },
  { id:"family",   jp:"家族",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"family" } } },
  { id:"photo",    jp:"写真",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"photo", note:"pic" } } },
  { id:"student",  jp:"学生",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"student" } } },
  { id:"station",  jp:"駅",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"station" } } },
  { id:"lang",     jp:"勉強している言語", pos:"名詞", cat:"名詞", content:false, tr:{ en:{ w:"the language I'm learning" } } },
  { id:"movie",    jp:"映画",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"movie" } } },
  { id:"resto",    jp:"飲食店", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"restaurant" } } },
  { id:"hotel",    jp:"ホテル", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"hotel" } } },
  { id:"mom",      jp:"母",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"mom" } } },
  { id:"dad",      jp:"父",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"dad" } } },
  { id:"woman",    jp:"女性",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"woman" } } },
  { id:"man",      jp:"男性",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"man" } } },
  { id:"train",    jp:"電車",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"train" } } },
  { id:"place",    jp:"場所",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"place" } } },
  { id:"brother",  jp:"兄弟",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"brother" } } },
  { id:"sister",   jp:"姉妹",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"sister" } } },
  { id:"problem",  jp:"問題",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"problem" } } },
  { id:"people",   jp:"人々",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"people" } } },
  { id:"shopping", jp:"買い物", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"shopping" } } },
  { id:"every_all",jp:"すべて", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"everything" } } },
  { id:"company",  jp:"会社",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"company", note:"work" } } },
  { id:"money",    jp:"お金",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"money" } } },
  { id:"time",     jp:"時間",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"time" } } },
  { id:"store",    jp:"店",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"store", note:"shop" } } },
  { id:"kid",      jp:"子ども", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"kid", note:"child" } } },
  { id:"weather",  jp:"天気",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"weather" } } },
  { id:"name",     jp:"名前",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"name" } } },
  { id:"rain",     jp:"雨",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"rain" } } },
  { id:"music",    jp:"音楽",   pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"music" } } },
  { id:"water",    jp:"水",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"water" } } },
  { id:"message",  jp:"メッセージ", pos:"名詞", cat:"名詞", content:true, tr:{ en:{ w:"message", note:"text" } } },
  { id:"bathroom", jp:"トイレ", pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"bathroom", note:"restroom" } } },
  { id:"book",     jp:"本",     pos:"名詞", cat:"名詞", content:true,  tr:{ en:{ w:"book" } } },

  // --- 副詞 ---
  { id:"very",     jp:"とても", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"very" } } },
  { id:"a_little", jp:"少し",   pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"a little" } } },
  { id:"maybe",    jp:"多分",   pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"maybe" } } },
  { id:"together", jp:"一緒に", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"together" } } },
  { id:"later",    jp:"あとで", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"later" } } },
  { id:"usually",  jp:"普通は", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"usually" } } },
  { id:"still",    jp:"まだ",   pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"still", note:"yet" } } },
  { id:"also",     jp:"〜もまた", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"also", note:"too" } } },
  { id:"often",    jp:"しばしば", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"often" } } },
  { id:"only",     jp:"〜だけ", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"only", note:"just" } } },
  { id:"about",    jp:"だいたい", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"about", note:"pretty much" } } },
  { id:"well",     jp:"上手に", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"well" } } },
  { id:"again",    jp:"また（再び）", pos:"副詞", cat:"副詞", content:false, tr:{ en:{ w:"again" } } },

  // --- 形容詞 ---
  { id:"nice",     jp:"優しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"nice", note:"kind" } } },
  { id:"tall",     jp:"（高さが）高い", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"tall", note:"high" } } },
  { id:"big",      jp:"大きい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"big" } } },
  { id:"small",    jp:"小さい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"small", note:"little" } } },
  { id:"hot",      jp:"暑い",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"hot" } } },
  { id:"hard",     jp:"難しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"hard", note:"difficult" } } },
  { id:"easy",     jp:"かんたんな", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"easy" } } },
  { id:"yummy",    jp:"美味しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"yummy", note:"delicious" } } },
  { id:"a_lot",    jp:"たくさんの", pos:"形容詞", cat:"形容詞", content:false, tr:{ en:{ w:"a lot of", note:"lots of" } } },
  { id:"different",jp:"異なった", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"different" } } },
  { id:"important",jp:"重要な", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"important" } } },
  { id:"famous",   jp:"有名な", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"famous" } } },
  { id:"fun",      jp:"面白い", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"fun", note:"interesting" } } },
  { id:"similar",  jp:"似ている", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"similar" } } },
  { id:"busy",     jp:"忙しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"busy" } } },
  { id:"long",     jp:"長い",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"long" } } },
  { id:"pretty",   jp:"美しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"beautiful", note:"pretty" } } },
  { id:"cheap",    jp:"（値段が）安い", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"cheap" } } },
  { id:"pricey",   jp:"（値段が）高い", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"expensive", note:"pricey" } } },
  { id:"sad",      jp:"悲しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"sad" } } },
  { id:"far",      jp:"遠い",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"far" } } },
  { id:"close",    jp:"近い",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"close", note:"near" } } },
  { id:"tired",    jp:"疲れている", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"tired" } } },
  { id:"hungry",   jp:"お腹が空いた", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"hungry" } } },
  { id:"new",      jp:"新しい", pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"new" } } },
  { id:"good",     jp:"良い",   pos:"形容詞", cat:"形容詞", content:true, tr:{ en:{ w:"good" } } },
  { id:"every",    jp:"毎〜",   pos:"形容詞", cat:"形容詞", content:false, tr:{ en:{ w:"every" } } },
  { id:"first",    jp:"初めの", pos:"形容詞", cat:"形容詞", content:false, tr:{ en:{ w:"first" } } },
  { id:"last",     jp:"前の",   pos:"形容詞", cat:"形容詞", content:false, tr:{ en:{ w:"last", note:"previous" } } },
  { id:"next",     jp:"次の",   pos:"形容詞", cat:"形容詞", content:false, tr:{ en:{ w:"next" } } },

  // --- 疑問詞 ---
  { id:"what",     jp:"何",     pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"what" } } },
  { id:"when",     jp:"いつ",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"when" } } },
  { id:"where",    jp:"どこ",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"where" } } },
  { id:"how",      jp:"どのように", pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"how" } } },
  { id:"how_much", jp:"いくら", pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"how much" } } },
  { id:"how_long", jp:"どのくらい（期間）", pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"how long" } } },
  { id:"why",      jp:"なぜ",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"why" } } },
  { id:"who",      jp:"誰",     pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"who" } } },
  { id:"which",    jp:"どの",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"which" } } },
  { id:"what_time",jp:"何時",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"what time" } } },
  { id:"how_old",  jp:"何歳",   pos:"疑問詞", cat:"疑問詞", content:false, tr:{ en:{ w:"how old" } } },

  // --- 接続詞 ---
  { id:"or",       jp:"または", pos:"接続詞", cat:"接続詞", content:false, tr:{ en:{ w:"or" } } },
  { id:"so",       jp:"だから", pos:"接続詞", cat:"接続詞", content:false, tr:{ en:{ w:"so" } } },
  { id:"but",      jp:"しかし", pos:"接続詞", cat:"接続詞", content:false, tr:{ en:{ w:"but" } } },
  { id:"and",      jp:"〜と〜", pos:"接続詞", cat:"接続詞", content:false, tr:{ en:{ w:"and" } } },

  // --- 前置詞 ---
  { id:"with",     jp:"〜と一緒に", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"with" } } },
  { id:"from",     jp:"〜から", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"from" } } },
  { id:"for",      jp:"〜のために", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"for" } } },
  { id:"of",       jp:"〜の（所有）", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"of" } } },
  { id:"at",       jp:"〜で（場所）", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"at", note:"in" } } },
  { id:"to",       jp:"〜へ（目的地）", pos:"前置詞", cat:"前置詞", content:false, tr:{ en:{ w:"to" } } },

  // --- 時と場所 ---
  { id:"here",     jp:"ここ",   pos:"副詞", cat:"時と場所", content:false, tr:{ en:{ w:"here" } } },
  { id:"there",    jp:"そこ",   pos:"副詞", cat:"時と場所", content:false, tr:{ en:{ w:"there" } } },
  { id:"today",    jp:"今日",   pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"today" } } },
  { id:"tomorrow", jp:"明日",   pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"tomorrow" } } },
  { id:"yesterday",jp:"昨日",   pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"yesterday" } } },
  { id:"day",      jp:"日",     pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"day" } } },
  { id:"week",     jp:"週",     pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"week" } } },
  { id:"month",    jp:"月",     pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"month" } } },
  { id:"year",     jp:"年",     pos:"名詞", cat:"時と場所", content:false, tr:{ en:{ w:"year" } } },
  { id:"now",      jp:"今",     pos:"副詞", cat:"時と場所", content:false, tr:{ en:{ w:"now" } } },

  // --- 数字 ---
  { id:"one",      jp:"1",      pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"one" } } },
  { id:"two",      jp:"2",      pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"two" } } },
  { id:"three",    jp:"3",      pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"three" } } },
  { id:"my_age",   jp:"自分の年齢の数字",   pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"(your age)" } } },
  { id:"birth_month", jp:"誕生日の月の数字", pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"(your birth month)" } } },
  { id:"birth_day",jp:"誕生日の日の数字",   pos:"数詞", cat:"数字", content:false, tr:{ en:{ w:"(your birth day)" } } },

  // --- 返答・相づち ---
  { id:"yes",      jp:"はい",   pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"yes", note:"yeah" } } },
  { id:"awesome",  jp:"すごい！", pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"awesome!", note:"cool!" } } },
  { id:"really",   jp:"そうなんですか？", pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"really?", note:"oh yeah?" } } },
  { id:"no",       jp:"いいえ", pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"no", note:"nope" } } },
  { id:"too_bad",  jp:"残念ですね", pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"that's too bad" } } },
  { id:"i_see",    jp:"なるほど", pos:"フレーズ", cat:"返答", content:false, tr:{ en:{ w:"I see", note:"got it" } } },

  // --- あいさつ ---
  { id:"g_morning",jp:"おはようございます", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"good morning" } } },
  { id:"hi",       jp:"こんにちは", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"hi", note:"hello" } } },
  { id:"g_evening",jp:"こんばんは", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"good evening" } } },
  { id:"bye",      jp:"さようなら", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"bye", note:"see you" } } },
  { id:"excuse_me",jp:"すみません（人を呼ぶとき）", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"excuse me" } } },
  { id:"thanks",   jp:"ありがとう", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"thanks", note:"thank you" } } },
  { id:"sorry",    jp:"ごめんなさい", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"sorry" } } },
  { id:"how_are_you", jp:"元気ですか？", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"how are you?", note:"how's it going?" } } },
  { id:"nice_meet",jp:"よろしくお願いします", pos:"フレーズ", cat:"あいさつ", content:false, tr:{ en:{ w:"nice to meet you" } } }
];

/* ============ 表現 expressions ============
 * id / jp(パターン) / cat / tr{ en:{ t:テンプレ } }  … {W} が単語スロット
 * すべて口語寄り。
 */
window.EXPRESSIONS = [
  // 現在
  { id:"e_am",       jp:"私は〜です（気持ち・身分）", cat:"現在", tr:{ en:{ t:"I'm {W}." } } },
  { id:"e_name",     jp:"私の名前は〜です",           cat:"現在", tr:{ en:{ t:"I'm {W}." } } },
  { id:"e_do",       jp:"〜する",                     cat:"現在", tr:{ en:{ t:"I {W}." } } },
  { id:"e_ing",      jp:"〜しているところだ",         cat:"現在", tr:{ en:{ t:"I'm {W} right now." } } },
  { id:"e_can",      jp:"〜できる",                   cat:"現在", tr:{ en:{ t:"I can {W}." } } },
  { id:"e_like",     jp:"〜が好きだ",                 cat:"現在", tr:{ en:{ t:"I like {W}." } } },
  // 過去
  { id:"e_was",      jp:"〜だった",                   cat:"過去", tr:{ en:{ t:"It was {W}." } } },
  { id:"e_did",      jp:"〜した",                     cat:"過去", tr:{ en:{ t:"I {W} yesterday." } } },
  // 経験
  { id:"e_have",     jp:"〜したことがある",           cat:"経験", tr:{ en:{ t:"I've {W} before." } } },
  { id:"e_been",     jp:"〜に行ったことがある",       cat:"経験", tr:{ en:{ t:"I've been to {W}." } } },
  // 時・条件
  { id:"e_if",       jp:"もし〜ならば",               cat:"時・条件", tr:{ en:{ t:"If {W}, tell me." } } },
  { id:"e_when",     jp:"〜のとき",                   cat:"時・条件", tr:{ en:{ t:"When {W}, call me." } } },
  // 依頼・提案
  { id:"e_please",   jp:"〜してください",             cat:"依頼・提案", tr:{ en:{ t:"Can you {W}?" } } },
  { id:"e_lets",     jp:"〜しましょう",               cat:"依頼・提案", tr:{ en:{ t:"Let's {W}." } } },
  // 意見・感想
  { id:"e_think",    jp:"〜だと思う",                 cat:"意見・感想", tr:{ en:{ t:"I think {W}." } } },
  { id:"e_wanna",    jp:"〜したい",                   cat:"意見・感想", tr:{ en:{ t:"I wanna {W}." } } },
  { id:"e_gotta",    jp:"〜しなければならない",       cat:"意見・感想", tr:{ en:{ t:"I gotta {W}." } } },
  { id:"e_is",       jp:"〜することは〇〇だ",          cat:"意見・感想", tr:{ en:{ t:"{W} is nice." } } },
  // 未来
  { id:"e_gonna",    jp:"〜するつもりだ",             cat:"未来", tr:{ en:{ t:"I'm gonna {W}." } } },
  // 質問
  { id:"e_are_you",  jp:"あなたは〜ですか？",         cat:"質問", tr:{ en:{ t:"Are you {W}?" } } },
  { id:"e_do_you",   jp:"あなたは〜しますか？",       cat:"質問", tr:{ en:{ t:"Do you {W}?" } } },
  { id:"e_have_you", jp:"あなたは〜したことがありますか？", cat:"質問", tr:{ en:{ t:"Have you ever {W}?" } } },
  { id:"e_qwhen", jp:"いつ〜しますか？",       cat:"質問", tr:{ en:{ t:"When do you {W}?" } } },
  { id:"e_where", jp:"どこで〜しますか？",     cat:"質問", tr:{ en:{ t:"Where do you {W}?" } } },
  { id:"e_how",   jp:"どのように〜しますか？", cat:"質問", tr:{ en:{ t:"How do you {W}?" } } },
  // 否定
  { id:"e_not",      jp:"〜ではない",                 cat:"否定", tr:{ en:{ t:"I'm not {W}." } } },
  { id:"e_dont",     jp:"〜しない",                   cat:"否定", tr:{ en:{ t:"I don't {W}." } } },
  { id:"e_cant",     jp:"〜できない",                 cat:"否定", tr:{ en:{ t:"I can't {W}." } } },
  { id:"e_never",    jp:"〜したことがない",           cat:"否定", tr:{ en:{ t:"I've never {W}." } } },
  { id:"e_dont_have",jp:"〜しなくてもよい",           cat:"否定", tr:{ en:{ t:"I don't have to {W}." } } }
];

/* ============ 例文 sentences ============
 * wordId / exprId / tr{ en:{ s:文, jp:対訳 } }
 * 同じ単語が違う exprId で複数登場 → 「満遍なく」を実現。すべて口語。
 */
window.SENTENCES = [
  // 名詞系
  { wordId:"friend", exprId:"e_like", tr:{ en:{ s:"I like my friends.",            jp:"友達が好き。" } } },
  { wordId:"friend", exprId:"e_wanna",tr:{ en:{ s:"I wanna see my friends.",        jp:"友達に会いたい。" } } },
  { wordId:"friend", exprId:"e_did",  tr:{ en:{ s:"I met a friend yesterday.",      jp:"昨日、友達に会った。" } } },
  { wordId:"food",   exprId:"e_like", tr:{ en:{ s:"I like Japanese food.",          jp:"日本食が好き。" } } },
  { wordId:"food",   exprId:"e_is",   tr:{ en:{ s:"This food is really good.",      jp:"この食べ物、めっちゃ美味しい。" } } },
  { wordId:"food",   exprId:"e_wanna",tr:{ en:{ s:"I wanna get some food.",         jp:"何か食べたい。" } } },
  { wordId:"movie",  exprId:"e_wanna",tr:{ en:{ s:"I wanna watch a movie tonight.", jp:"今夜、映画が観たい。" } } },
  { wordId:"movie",  exprId:"e_did",  tr:{ en:{ s:"I watched a movie last night.",  jp:"昨夜、映画を観た。" } } },
  { wordId:"movie",  exprId:"e_gonna",tr:{ en:{ s:"I'm gonna see a movie later.",   jp:"あとで映画を観るつもり。" } } },
  { wordId:"car",    exprId:"e_have",  tr:{ en:{ s:"I've had this car for years.",  jp:"この車、何年も乗ってる。" } } },
  { wordId:"car",    exprId:"e_gonna", tr:{ en:{ s:"I'm gonna buy a new car.",      jp:"新しい車を買うつもり。" } } },
  { wordId:"family", exprId:"e_like",  tr:{ en:{ s:"I love my family.",             jp:"家族が大好き。" } } },
  { wordId:"family", exprId:"e_am",    tr:{ en:{ s:"I'm with my family now.",       jp:"今、家族と一緒。" } } },
  { wordId:"photo",  exprId:"e_wanna", tr:{ en:{ s:"I wanna take a photo.",         jp:"写真を撮りたい。" } } },
  { wordId:"photo",  exprId:"e_can",   tr:{ en:{ s:"Can you take a photo?",         jp:"写真、撮ってくれる？" } } },
  { wordId:"station",exprId:"e_been",  tr:{ en:{ s:"I've been to that station.",    jp:"あの駅、行ったことある。" } } },
  { wordId:"station",exprId:"e_where", tr:{ en:{ s:"Where's the station?",          jp:"駅はどこ？" } } },
  { wordId:"hotel",  exprId:"e_been",  tr:{ en:{ s:"I've been to this hotel.",      jp:"このホテル、来たことある。" } } },
  { wordId:"hotel",  exprId:"e_is",    tr:{ en:{ s:"This hotel is really nice.",    jp:"このホテル、すごくいい。" } } },
  { wordId:"train",  exprId:"e_did",   tr:{ en:{ s:"I took the train today.",       jp:"今日は電車に乗った。" } } },
  { wordId:"train",  exprId:"e_gonna", tr:{ en:{ s:"I'm gonna catch the train.",    jp:"電車に乗るつもり。" } } },
  { wordId:"money",  exprId:"e_dont_have", tr:{ en:{ s:"I don't have much money.",  jp:"あんまりお金がない。" } } },
  { wordId:"money",  exprId:"e_gotta", tr:{ en:{ s:"I gotta save money.",           jp:"お金を貯めなきゃ。" } } },
  { wordId:"time",   exprId:"e_dont_have", tr:{ en:{ s:"I don't have time today.",  jp:"今日は時間がない。" } } },
  { wordId:"time",   exprId:"e_do_you", tr:{ en:{ s:"Do you have time?",          jp:"時間ある？" } } },
  { wordId:"shopping",exprId:"e_wanna", tr:{ en:{ s:"I wanna go shopping.",         jp:"買い物に行きたい。" } } },
  { wordId:"shopping",exprId:"e_lets",  tr:{ en:{ s:"Let's go shopping!",           jp:"買い物に行こう！" } } },
  { wordId:"music",  exprId:"e_like",   tr:{ en:{ s:"I like this music.",           jp:"この音楽が好き。" } } },
  { wordId:"music",  exprId:"e_ing",    tr:{ en:{ s:"I'm listening to music right now.", jp:"今、音楽を聴いてる。" } } },
  { wordId:"book",   exprId:"e_ing",    tr:{ en:{ s:"I'm reading a book right now.", jp:"今、本を読んでる。" } } },
  { wordId:"book",   exprId:"e_have",   tr:{ en:{ s:"I've read this book before.",  jp:"この本、読んだことある。" } } },
  { wordId:"water",  exprId:"e_wanna",  tr:{ en:{ s:"I wanna drink some water.",    jp:"水が飲みたい。" } } },
  { wordId:"water",  exprId:"e_can",    tr:{ en:{ s:"Can you get me some water?",   jp:"水をもらえる？" } } },
  { wordId:"bathroom",exprId:"e_where", tr:{ en:{ s:"Where's the bathroom?",        jp:"トイレはどこ？" } } },
  { wordId:"message",exprId:"e_gonna",  tr:{ en:{ s:"I'm gonna send you a message.",jp:"メッセージ送るね。" } } },
  { wordId:"weather",exprId:"e_is",     tr:{ en:{ s:"The weather is nice today.",   jp:"今日は天気がいい。" } } },
  { wordId:"weather",exprId:"e_was",    tr:{ en:{ s:"The weather was bad yesterday.",jp:"昨日は天気が悪かった。" } } },
  { wordId:"rain",   exprId:"e_ing",    tr:{ en:{ s:"It's raining right now.",      jp:"今、雨が降ってる。" } } },
  { wordId:"kid",    exprId:"e_was",    tr:{ en:{ s:"I was a shy kid.",             jp:"私は内気な子どもだった。" } } },
  { wordId:"name",   exprId:"e_name",   tr:{ en:{ s:"I'm Yuta.",                    jp:"私はユウタです。" } } },
  { wordId:"morning",exprId:"e_do",     tr:{ en:{ s:"I run in the morning.",        jp:"朝に走る。" } } },
  { wordId:"night",  exprId:"e_do",     tr:{ en:{ s:"I read at night.",             jp:"夜に本を読む。" } } },
  { wordId:"people", exprId:"e_like",   tr:{ en:{ s:"I like meeting new people.",   jp:"新しい人に会うのが好き。" } } },
  { wordId:"place",  exprId:"e_been",   tr:{ en:{ s:"I've been to this place.",     jp:"この場所、来たことある。" } } },
  { wordId:"store",  exprId:"e_gonna",  tr:{ en:{ s:"I'm gonna go to the store.",   jp:"店に行くつもり。" } } },
  { wordId:"company",exprId:"e_do",     tr:{ en:{ s:"I work at a big company.",     jp:"大きい会社で働いてる。" } } },
  { wordId:"culture",exprId:"e_like",   tr:{ en:{ s:"I like Japanese culture.",     jp:"日本の文化が好き。" } } },
  { wordId:"problem",exprId:"e_is",     tr:{ en:{ s:"That's a big problem.",        jp:"それは大きな問題だ。" } } },
  { wordId:"home",   exprId:"e_am",     tr:{ en:{ s:"I'm at home now.",             jp:"今、家にいる。" } } },
  { wordId:"home",   exprId:"e_wanna",  tr:{ en:{ s:"I wanna go home.",             jp:"家に帰りたい。" } } },
  { wordId:"student",exprId:"e_am",     tr:{ en:{ s:"I'm a student.",               jp:"私は学生です。" } } },
  { wordId:"japanese",exprId:"e_am",    tr:{ en:{ s:"I'm Japanese.",                jp:"私は日本人です。" } } },
  { wordId:"mom",    exprId:"e_gonna",  tr:{ en:{ s:"I'm gonna call my mom.",       jp:"母に電話するつもり。" } } },
  { wordId:"dad",    exprId:"e_is",     tr:{ en:{ s:"My dad is really tall.",       jp:"父はとても背が高い。" } } },

  // 形容詞系
  { wordId:"tired",  exprId:"e_am",     tr:{ en:{ s:"I'm so tired today.",          jp:"今日はすごく疲れてる。" } } },
  { wordId:"tired",  exprId:"e_was",    tr:{ en:{ s:"I was tired yesterday.",       jp:"昨日は疲れてた。" } } },
  { wordId:"hungry", exprId:"e_am",     tr:{ en:{ s:"I'm hungry right now.",        jp:"今、お腹すいてる。" } } },
  { wordId:"hungry", exprId:"e_are_you",tr:{ en:{ s:"Are you hungry?",              jp:"お腹すいてる？" } } },
  { wordId:"busy",   exprId:"e_am",     tr:{ en:{ s:"I'm busy today.",              jp:"今日は忙しい。" } } },
  { wordId:"busy",   exprId:"e_are_you",tr:{ en:{ s:"Are you busy now?",            jp:"今、忙しい？" } } },
  { wordId:"good",   exprId:"e_am",     tr:{ en:{ s:"I'm good, thanks.",            jp:"元気だよ、ありがとう。" } } },
  { wordId:"good",   exprId:"e_is",     tr:{ en:{ s:"This is really good.",         jp:"これ、すごくいい。" } } },
  { wordId:"nice",   exprId:"e_is",     tr:{ en:{ s:"My friend is so nice.",         jp:"私の友達はとても優しい。" } } },
  { wordId:"big",    exprId:"e_is",     tr:{ en:{ s:"This city is big.",            jp:"この街は大きい。" } } },
  { wordId:"small",  exprId:"e_is",     tr:{ en:{ s:"My room is small.",            jp:"私の部屋は小さい。" } } },
  { wordId:"hot",    exprId:"e_is",     tr:{ en:{ s:"It's really hot today.",       jp:"今日はすごく暑い。" } } },
  { wordId:"hot",    exprId:"e_was",    tr:{ en:{ s:"It was hot yesterday.",        jp:"昨日は暑かった。" } } },
  { wordId:"hard",   exprId:"e_is",     tr:{ en:{ s:"This is kinda hard.",          jp:"これ、ちょっと難しい。" } } },
  { wordId:"easy",   exprId:"e_is",     tr:{ en:{ s:"That test was easy.",          jp:"あのテストは簡単だった。" } } },
  { wordId:"yummy",  exprId:"e_is",     tr:{ en:{ s:"This is so yummy!",            jp:"これ、めっちゃ美味しい！" } } },
  { wordId:"famous", exprId:"e_is",     tr:{ en:{ s:"This place is famous.",        jp:"この場所は有名だ。" } } },
  { wordId:"fun",    exprId:"e_is",     tr:{ en:{ s:"This game is really fun.",     jp:"このゲーム、すごく面白い。" } } },
  { wordId:"fun",    exprId:"e_was",    tr:{ en:{ s:"It was fun!",                  jp:"楽しかった！" } } },
  { wordId:"cheap",  exprId:"e_is",     tr:{ en:{ s:"This one is cheap.",           jp:"これは安い。" } } },
  { wordId:"pricey", exprId:"e_is",     tr:{ en:{ s:"That's too expensive.",        jp:"それは高すぎる。" } } },
  { wordId:"sad",    exprId:"e_am",     tr:{ en:{ s:"I'm a little sad today.",      jp:"今日はちょっと悲しい。" } } },
  { wordId:"new",    exprId:"e_is",     tr:{ en:{ s:"My phone is new.",             jp:"私のスマホは新しい。" } } },
  { wordId:"close",  exprId:"e_is",     tr:{ en:{ s:"The station is close.",        jp:"駅は近い。" } } },
  { wordId:"far",    exprId:"e_is",     tr:{ en:{ s:"The airport is far.",          jp:"空港は遠い。" } } },
  { wordId:"important",exprId:"e_is",   tr:{ en:{ s:"This is really important.",     jp:"これはとても重要だ。" } } },
  { wordId:"different",exprId:"e_is",   tr:{ en:{ s:"This one is different.",        jp:"これは違う。" } } },
  { wordId:"similar",exprId:"e_is",     tr:{ en:{ s:"We're pretty similar.",         jp:"私たちはけっこう似てる。" } } },
  { wordId:"pretty", exprId:"e_is",     tr:{ en:{ s:"The view is beautiful.",       jp:"景色が美しい。" } } },
  { wordId:"long",   exprId:"e_is",     tr:{ en:{ s:"The movie is long.",           jp:"その映画は長い。" } } },
  { wordId:"tall",   exprId:"e_is",     tr:{ en:{ s:"My brother is really tall.",    jp:"私の兄弟は背が高い。" } } },

  // 追加: 例文ゼロだった6語を補完（全65 content語カバー）
  { wordId:"resto",     exprId:"e_wanna", tr:{ en:{ s:"I wanna try that restaurant.",       jp:"あの飲食店に行ってみたい。" } } },
  { wordId:"resto",     exprId:"e_been",  tr:{ en:{ s:"I've been to this restaurant.",      jp:"この飲食店、来たことある。" } } },
  { wordId:"woman",     exprId:"e_is",    tr:{ en:{ s:"That woman is really nice.",         jp:"あの女性はとても優しい。" } } },
  { wordId:"woman",     exprId:"e_did",   tr:{ en:{ s:"I met a woman at the party.",        jp:"パーティーで女性に会った。" } } },
  { wordId:"man",       exprId:"e_is",    tr:{ en:{ s:"That man is really tall.",           jp:"あの男性はとても背が高い。" } } },
  { wordId:"man",       exprId:"e_did",   tr:{ en:{ s:"I talked to a man yesterday.",       jp:"昨日、男性と話した。" } } },
  { wordId:"brother",   exprId:"e_is",    tr:{ en:{ s:"My brother is really tall.",         jp:"私の兄弟は背が高い。" } } },
  { wordId:"brother",   exprId:"e_like",  tr:{ en:{ s:"I like hanging out with my brother.",jp:"兄弟と過ごすのが好き。" } } },
  { wordId:"sister",    exprId:"e_is",    tr:{ en:{ s:"My sister is really kind.",          jp:"私の姉妹はとても優しい。" } } },
  { wordId:"sister",    exprId:"e_did",   tr:{ en:{ s:"I called my sister yesterday.",      jp:"昨日、姉妹に電話した。" } } },
  { wordId:"every_all", exprId:"e_is",    tr:{ en:{ s:"Everything is fine.",                jp:"すべて順調だ。" } } },
  { wordId:"every_all", exprId:"e_like",  tr:{ en:{ s:"I like everything here.",            jp:"ここのすべてが好き。" } } },

  // === 動詞36語の例文（各2文・表現を散らして満遍なく） ===
  { wordId:"go",       exprId:"e_wanna", tr:{ en:{ s:"I wanna go now.",              jp:"もう行きたい。" } } },
  { wordId:"go",       exprId:"e_gonna", tr:{ en:{ s:"I'm gonna go there.",          jp:"そこに行くつもり。" } } },
  { wordId:"come",     exprId:"e_please",tr:{ en:{ s:"Can you come here?",           jp:"ここに来てくれる？" } } },
  { wordId:"come",     exprId:"e_did",   tr:{ en:{ s:"She came yesterday.",          jp:"彼女は昨日来た。" } } },
  { wordId:"live",     exprId:"e_do",    tr:{ en:{ s:"I live in Tokyo.",             jp:"東京に住んでる。" } } },
  { wordId:"live",     exprId:"e_wanna", tr:{ en:{ s:"I wanna live abroad.",         jp:"外国に住みたい。" } } },
  { wordId:"eat",      exprId:"e_wanna", tr:{ en:{ s:"I wanna eat something.",       jp:"何か食べたい。" } } },
  { wordId:"eat",      exprId:"e_did",   tr:{ en:{ s:"I ate a lot.",                 jp:"たくさん食べた。" } } },
  { wordId:"buy",      exprId:"e_gonna", tr:{ en:{ s:"I'm gonna buy it.",            jp:"それを買うつもり。" } } },
  { wordId:"buy",      exprId:"e_wanna", tr:{ en:{ s:"I wanna buy new shoes.",       jp:"新しい靴を買いたい。" } } },
  { wordId:"see",      exprId:"e_can",   tr:{ en:{ s:"I can see it.",                jp:"それが見える。" } } },
  { wordId:"see",      exprId:"e_wanna", tr:{ en:{ s:"I wanna see you.",             jp:"あなたに会いたい。" } } },
  { wordId:"use",      exprId:"e_please",tr:{ en:{ s:"Can I use this?",              jp:"これ使ってもいい？" } } },
  { wordId:"use",      exprId:"e_do",    tr:{ en:{ s:"I use it every day.",          jp:"毎日使ってる。" } } },
  { wordId:"hear",     exprId:"e_can",   tr:{ en:{ s:"I can hear you.",              jp:"聞こえるよ。" } } },
  { wordId:"hear",     exprId:"e_did",   tr:{ en:{ s:"I heard the news.",            jp:"そのニュースを聞いた。" } } },
  { wordId:"wake",     exprId:"e_did",   tr:{ en:{ s:"I woke up early.",             jp:"早く起きた。" } } },
  { wordId:"wake",     exprId:"e_gotta", tr:{ en:{ s:"I gotta wake up early.",       jp:"早く起きなきゃ。" } } },
  { wordId:"sleep",    exprId:"e_wanna", tr:{ en:{ s:"I wanna sleep.",               jp:"寝たい。" } } },
  { wordId:"sleep",    exprId:"e_gotta", tr:{ en:{ s:"I gotta sleep now.",           jp:"もう寝なきゃ。" } } },
  { wordId:"speak",    exprId:"e_can",   tr:{ en:{ s:"I can speak a little.",        jp:"少し話せる。" } } },
  { wordId:"speak",    exprId:"e_wanna", tr:{ en:{ s:"I wanna speak English.",       jp:"英語を話したい。" } } },
  { wordId:"say",      exprId:"e_wanna", tr:{ en:{ s:"I wanna say something.",       jp:"何か言いたい。" } } },
  { wordId:"say",      exprId:"e_did",   tr:{ en:{ s:"He said yes.",                 jp:"彼ははいと言った。" } } },
  { wordId:"talk",     exprId:"e_wanna", tr:{ en:{ s:"I wanna talk with you.",       jp:"あなたと話したい。" } } },
  { wordId:"talk",     exprId:"e_lets",  tr:{ en:{ s:"Let's talk later.",            jp:"あとで話そう。" } } },
  { wordId:"work",     exprId:"e_do",    tr:{ en:{ s:"I work every day.",            jp:"毎日働いてる。" } } },
  { wordId:"work",     exprId:"e_gotta", tr:{ en:{ s:"I gotta work tomorrow.",       jp:"明日働かなきゃ。" } } },
  { wordId:"know",     exprId:"e_do",    tr:{ en:{ s:"I know him.",                  jp:"彼を知ってる。" } } },
  { wordId:"know",     exprId:"e_dont",  tr:{ en:{ s:"I don't know.",                jp:"わからない。" } } },
  { wordId:"meet",     exprId:"e_wanna", tr:{ en:{ s:"I wanna meet your family.",    jp:"あなたの家族に会いたい。" } } },
  { wordId:"meet",     exprId:"e_did",   tr:{ en:{ s:"I met a friend.",              jp:"友達に会った。" } } },
  { wordId:"wait",     exprId:"e_please",tr:{ en:{ s:"Can you wait?",                jp:"待ってくれる？" } } },
  { wordId:"wait",     exprId:"e_gotta", tr:{ en:{ s:"I gotta wait here.",           jp:"ここで待たなきゃ。" } } },
  { wordId:"write",    exprId:"e_please",tr:{ en:{ s:"Can you write it?",            jp:"それ書いてくれる？" } } },
  { wordId:"write",    exprId:"e_wanna", tr:{ en:{ s:"I wanna write a book.",        jp:"本を書きたい。" } } },
  { wordId:"have",     exprId:"e_do",    tr:{ en:{ s:"I have a car.",                jp:"車を持ってる。" } } },
  { wordId:"have",     exprId:"e_dont",  tr:{ en:{ s:"I don't have money.",          jp:"お金がない。" } } },
  { wordId:"start",    exprId:"e_did",   tr:{ en:{ s:"The movie started.",           jp:"映画が始まった。" } } },
  { wordId:"start",    exprId:"e_gonna", tr:{ en:{ s:"It's gonna start soon.",       jp:"もうすぐ始まる。" } } },
  { wordId:"finish",   exprId:"e_did",   tr:{ en:{ s:"I finished my work.",          jp:"仕事が終わった。" } } },
  { wordId:"finish",   exprId:"e_gotta", tr:{ en:{ s:"I gotta finish this.",         jp:"これを終わらせなきゃ。" } } },
  { wordId:"think",    exprId:"e_do",    tr:{ en:{ s:"I think so.",                  jp:"そう思う。" } } },
  { wordId:"think",    exprId:"e_dont",  tr:{ en:{ s:"I don't think so.",            jp:"そうは思わない。" } } },
  { wordId:"send",     exprId:"e_gonna", tr:{ en:{ s:"I'm gonna send a message.",    jp:"メッセージ送るね。" } } },
  { wordId:"send",     exprId:"e_please",tr:{ en:{ s:"Can you send it?",             jp:"それ送ってくれる？" } } },
  { wordId:"understand",exprId:"e_do",   tr:{ en:{ s:"I understand.",                jp:"わかった。" } } },
  { wordId:"understand",exprId:"e_dont", tr:{ en:{ s:"I don't understand.",          jp:"わからない。" } } },
  { wordId:"read",     exprId:"e_ing",   tr:{ en:{ s:"I'm reading a book right now.",jp:"今、本を読んでる。" } } },
  { wordId:"read",     exprId:"e_like",  tr:{ en:{ s:"I like to read.",              jp:"読むのが好き。" } } },
  { wordId:"help",     exprId:"e_please",tr:{ en:{ s:"Can you help me?",             jp:"手伝ってくれる？" } } },
  { wordId:"help",     exprId:"e_wanna", tr:{ en:{ s:"I wanna help you.",            jp:"手伝いたい。" } } },
  { wordId:"like",     exprId:"e_do",    tr:{ en:{ s:"I like it.",                   jp:"それが好き。" } } },
  { wordId:"like",     exprId:"e_dont",  tr:{ en:{ s:"I don't like it.",             jp:"それは好きじゃない。" } } },
  { wordId:"enter",    exprId:"e_please",tr:{ en:{ s:"Can I go in?",                 jp:"入ってもいい？" } } },
  { wordId:"enter",    exprId:"e_did",   tr:{ en:{ s:"I went in.",                   jp:"中に入った。" } } },
  { wordId:"arrive",   exprId:"e_did",   tr:{ en:{ s:"I arrived at the station.",    jp:"駅に着いた。" } } },
  { wordId:"arrive",   exprId:"e_gonna", tr:{ en:{ s:"I'm gonna arrive soon.",       jp:"もうすぐ着く。" } } },
  { wordId:"remember", exprId:"e_do",    tr:{ en:{ s:"I remember you.",              jp:"あなたを覚えてる。" } } },
  { wordId:"remember", exprId:"e_dont",  tr:{ en:{ s:"I don't remember.",            jp:"覚えてない。" } } },
  { wordId:"quit",     exprId:"e_gonna", tr:{ en:{ s:"I'm gonna quit smoking.",      jp:"タバコをやめるつもり。" } } },
  { wordId:"quit",     exprId:"e_wanna", tr:{ en:{ s:"I wanna quit my job.",         jp:"仕事を辞めたい。" } } },
  { wordId:"become",   exprId:"e_wanna", tr:{ en:{ s:"I wanna become a teacher.",    jp:"先生になりたい。" } } },
  { wordId:"become",   exprId:"e_gonna", tr:{ en:{ s:"It's gonna become popular.",   jp:"人気になるよ。" } } },
  { wordId:"study",    exprId:"e_gotta", tr:{ en:{ s:"I gotta study tonight.",       jp:"今夜勉強しなきゃ。" } } },
  { wordId:"study",    exprId:"e_ing",   tr:{ en:{ s:"I'm studying right now.",      jp:"今、勉強してる。" } } },
  { wordId:"ride",     exprId:"e_wanna", tr:{ en:{ s:"I wanna take the train.",      jp:"電車に乗りたい。" } } },
  { wordId:"ride",     exprId:"e_did",   tr:{ en:{ s:"I took a taxi.",               jp:"タクシーに乗った。" } } },
  { wordId:"go_home",  exprId:"e_wanna", tr:{ en:{ s:"I wanna go home.",             jp:"家に帰りたい。" } } },
  { wordId:"go_home",  exprId:"e_gonna", tr:{ en:{ s:"I'm gonna go home now.",       jp:"もう帰るつもり。" } } },

  // === 追加形容詞4語 ===
  { wordId:"happy",    exprId:"e_am",    tr:{ en:{ s:"I'm so happy today.",          jp:"今日はすごく嬉しい。" } } },
  { wordId:"happy",    exprId:"e_are_you",tr:{ en:{ s:"Are you happy?",              jp:"嬉しい？" } } },
  { wordId:"favorite", exprId:"e_is",    tr:{ en:{ s:"This is my favorite.",         jp:"これがお気に入り。" } } },
  { wordId:"favorite", exprId:"e_was",   tr:{ en:{ s:"That was my favorite.",        jp:"あれがお気に入りだった。" } } },
  { wordId:"foreign",  exprId:"e_is",    tr:{ en:{ s:"This is a foreign country.",   jp:"ここは外国だ。" } } },
  { wordId:"foreign",  exprId:"e_like",  tr:{ en:{ s:"I like foreign movies.",       jp:"外国の映画が好き。" } } },
  { wordId:"smart",    exprId:"e_is",    tr:{ en:{ s:"She's really smart.",          jp:"彼女はとても賢い。" } } },
  { wordId:"smart",    exprId:"e_is",    tr:{ en:{ s:"My sister is really smart.",    jp:"私の姉妹はとても賢い。" } } },

  // === 表現を散らす追加（未使用7表現＋レア表現を補充） ===
  // もし〜ならば / 〜のとき
  { wordId:"busy",   exprId:"e_if",     tr:{ en:{ s:"If you're busy, tell me.",       jp:"もし忙しかったら教えて。" } } },
  { wordId:"hungry", exprId:"e_if",     tr:{ en:{ s:"If you're hungry, let's eat.",   jp:"もしお腹すいてたら食べよう。" } } },
  { wordId:"arrive", exprId:"e_when",   tr:{ en:{ s:"When you arrive, call me.",      jp:"着いたら電話して。" } } },
  { wordId:"finish", exprId:"e_when",   tr:{ en:{ s:"When I finish, I'll go home.",   jp:"終わったら帰る。" } } },
  // 〜だと思う
  { wordId:"good",     exprId:"e_think",tr:{ en:{ s:"I think it's good.",              jp:"いいと思う。" } } },
  { wordId:"important",exprId:"e_think",tr:{ en:{ s:"I think this is important.",      jp:"これは大事だと思う。" } } },
  { wordId:"famous",   exprId:"e_think",tr:{ en:{ s:"I think she's famous.",           jp:"彼女は有名だと思う。" } } },
  // あなたは〜しますか？
  { wordId:"eat",    exprId:"e_do_you", tr:{ en:{ s:"Do you eat meat?",               jp:"肉は食べる？" } } },
  { wordId:"know",   exprId:"e_do_you", tr:{ en:{ s:"Do you know him?",               jp:"彼を知ってる？" } } },
  { wordId:"study",  exprId:"e_do_you", tr:{ en:{ s:"Do you study every day?",        jp:"毎日勉強する？" } } },
  // 〜ではない
  { wordId:"busy",   exprId:"e_not",    tr:{ en:{ s:"I'm not busy today.",            jp:"今日は忙しくない。" } } },
  { wordId:"tired",  exprId:"e_not",    tr:{ en:{ s:"I'm not tired.",                 jp:"疲れてない。" } } },
  { wordId:"student",exprId:"e_not",    tr:{ en:{ s:"I'm not a student.",             jp:"私は学生じゃない。" } } },
  // 〜できない
  { wordId:"come",   exprId:"e_cant",   tr:{ en:{ s:"I can't come today.",            jp:"今日は行けない。" } } },
  { wordId:"speak",  exprId:"e_cant",   tr:{ en:{ s:"I can't speak French.",          jp:"フランス語は話せない。" } } },
  { wordId:"wait",   exprId:"e_cant",   tr:{ en:{ s:"I can't wait!",                  jp:"待ちきれない！" } } },
  // 〜したことがない
  { wordId:"eat",    exprId:"e_never",  tr:{ en:{ s:"I've never eaten that.",         jp:"それ食べたことない。" } } },
  { wordId:"meet",   exprId:"e_never",  tr:{ en:{ s:"I've never met him.",            jp:"彼に会ったことない。" } } },
  { wordId:"see",    exprId:"e_never",  tr:{ en:{ s:"I've never seen it.",            jp:"それ見たことない。" } } },
  // レア表現の補充
  { wordId:"movie",  exprId:"e_have_you",tr:{ en:{ s:"Have you ever seen this movie?",jp:"この映画観たことある？" } } },
  { wordId:"study",  exprId:"e_have",   tr:{ en:{ s:"I've studied English before.",   jp:"前に英語を勉強したことある。" } } },
  { wordId:"eat",    exprId:"e_lets",   tr:{ en:{ s:"Let's eat!",                     jp:"食べよう！" } } },
  { wordId:"meet",   exprId:"e_lets",   tr:{ en:{ s:"Let's meet tomorrow.",           jp:"明日会おう。" } } },
  { wordId:"live",   exprId:"e_where",  tr:{ en:{ s:"Where do you live?",             jp:"どこに住んでるの？" } } },
  { wordId:"work",   exprId:"e_where",  tr:{ en:{ s:"Where do you work?",             jp:"どこで働いてるの？" } } },
  { wordId:"study",  exprId:"e_dont_have",tr:{ en:{ s:"I don't have to study today.", jp:"今日は勉強しなくていい。" } } },
  { wordId:"work",   exprId:"e_dont_have",tr:{ en:{ s:"I don't have to work tomorrow.",jp:"明日は働かなくていい。" } } },

  // === Day1 例文（動詞20語×各1文・表現バラけ・語彙を組み合わせ・hl=強調位置） ===
  { wordId:"go",    exprId:"e_gonna",  hl:"go",     tr:{ en:{ s:"I'm gonna go to the station.",   jp:"駅に行くつもり。" } } },
  { wordId:"come",  exprId:"e_qwhen",  hl:"come",   tr:{ en:{ s:"When do you come home?",          jp:"いつ家に来るの？" } } },
  { wordId:"live",  exprId:"e_where",  hl:"live",   tr:{ en:{ s:"Where do you live now?",          jp:"今どこに住んでるの？" } } },
  { wordId:"eat",   exprId:"e_lets",   hl:"eat",    tr:{ en:{ s:"Let's eat together.",             jp:"一緒に食べよう。" } } },
  { wordId:"buy",   exprId:"e_do_you", hl:"buy",    tr:{ en:{ s:"Do you buy food here?",           jp:"ここで食べ物を買う？" } } },
  { wordId:"see",   exprId:"e_can",    hl:"see",    tr:{ en:{ s:"I can see the train.",            jp:"電車が見える。" } } },
  { wordId:"use",   exprId:"e_did",    hl:"used",   tr:{ en:{ s:"I used it yesterday.",            jp:"昨日それを使った。" } } },
  { wordId:"hear",  exprId:"e_did",    hl:"heard",  tr:{ en:{ s:"I heard the news at work.",       jp:"職場でニュースを聞いた。" } } },
  { wordId:"wake",  exprId:"e_gotta",  hl:"wake up",tr:{ en:{ s:"I gotta wake up early tomorrow.", jp:"明日早く起きなきゃ。" } } },
  { wordId:"sleep", exprId:"e_wanna",  hl:"sleep",  tr:{ en:{ s:"I wanna sleep now.",              jp:"今すぐ寝たい。" } } },
  { wordId:"speak", exprId:"e_do",     hl:"speak",  tr:{ en:{ s:"I speak two languages.",          jp:"2つの言語を話す。" } } },
  { wordId:"say",   exprId:"e_did",    hl:"said",   tr:{ en:{ s:"He said something good.",         jp:"彼はいいことを言った。" } } },
  { wordId:"talk",  exprId:"e_wanna",  hl:"talk",   tr:{ en:{ s:"I wanna talk to your family.",    jp:"あなたの家族と話したい。" } } },
  { wordId:"work",  exprId:"e_do",     hl:"work",   tr:{ en:{ s:"I work every day.",               jp:"毎日働いている。" } } },
  { wordId:"know",  exprId:"e_dont",   hl:"know",   tr:{ en:{ s:"I don't know your name.",         jp:"あなたの名前を知らない。" } } },
  { wordId:"meet",  exprId:"e_qwhen",  hl:"meet",   tr:{ en:{ s:"When do you meet your friends?",  jp:"いつ友達に会うの？" } } },
  { wordId:"wait",  exprId:"e_please", hl:"wait",   tr:{ en:{ s:"Can you wait here?",              jp:"ここで待ってくれる？" } } },
  { wordId:"write", exprId:"e_ing",    hl:"writing",tr:{ en:{ s:"I'm writing a message now.",      jp:"今メッセージを書いている。" } } },
  { wordId:"have",  exprId:"e_dont",   hl:"have",   tr:{ en:{ s:"I don't have money now.",         jp:"今お金がない。" } } },
  { wordId:"start", exprId:"e_qwhen",  hl:"start",  tr:{ en:{ s:"When do you start work?",         jp:"いつ仕事を始めるの？" } } },

  // === 残りの単語ぶんの英語例文（各語1文・強調位置つき） ===
  // 副詞
  { wordId:"very",     exprId:"e_is",     hl:"very",     tr:{ en:{ s:"It's very hot today.",            jp:"今日はとても暑い。" } } },
  { wordId:"a_little", exprId:"e_am",     hl:"a little",  tr:{ en:{ s:"I'm a little tired.",             jp:"少し疲れてる。" } } },
  { wordId:"maybe",    exprId:"e_gonna",  hl:"Maybe",     tr:{ en:{ s:"Maybe I'm gonna go tomorrow.",    jp:"多分明日行くつもり。" } } },
  { wordId:"together", exprId:"e_lets",   hl:"together",  tr:{ en:{ s:"Let's study together.",           jp:"一緒に勉強しよう。" } } },
  { wordId:"later",    exprId:"e_lets",   hl:"later",     tr:{ en:{ s:"Let's talk later.",              jp:"あとで話そう。" } } },
  { wordId:"usually",  exprId:"e_do",     hl:"usually",   tr:{ en:{ s:"I usually wake up early.",        jp:"普段は早く起きる。" } } },
  { wordId:"still",    exprId:"e_ing",    hl:"still",     tr:{ en:{ s:"I'm still working.",             jp:"まだ働いてる。" } } },
  { wordId:"also",     exprId:"e_do",     hl:"also",      tr:{ en:{ s:"I also speak English.",           jp:"私も英語を話す。" } } },
  { wordId:"often",    exprId:"e_do",     hl:"often",     tr:{ en:{ s:"I often see my friends.",         jp:"よく友達に会う。" } } },
  { wordId:"only",     exprId:"e_have",   hl:"only",      tr:{ en:{ s:"I only have one car.",            jp:"車は1台だけ。" } } },
  { wordId:"about",    exprId:"e_is",     hl:"about",     tr:{ en:{ s:"It's about ten dollars.",         jp:"だいたい10ドル。" } } },
  { wordId:"well",     exprId:"e_can",    hl:"well",      tr:{ en:{ s:"I can speak English well.",       jp:"英語を上手に話せる。" } } },
  { wordId:"again",    exprId:"e_lets",   hl:"again",     tr:{ en:{ s:"Let's meet again.",              jp:"また会おう。" } } },
  // 前置詞
  { wordId:"with",     exprId:"e_wanna",  hl:"with",      tr:{ en:{ s:"I wanna go with you.",            jp:"あなたと行きたい。" } } },
  { wordId:"from",     exprId:"e_am",     hl:"from",      tr:{ en:{ s:"I'm from Japan.",                 jp:"私は日本出身です。" } } },
  { wordId:"for",      exprId:"e_did",    hl:"for",       tr:{ en:{ s:"I bought food for you.",          jp:"あなたに食べ物を買った。" } } },
  { wordId:"of",       exprId:"e_is",     hl:"of",        tr:{ en:{ s:"He's a friend of mine.",          jp:"彼は私の友達だ。" } } },
  { wordId:"at",       exprId:"e_am",     hl:"at",        tr:{ en:{ s:"I'm at home now.",               jp:"今、家にいる。" } } },
  { wordId:"to",       exprId:"e_gonna",  hl:"to",        tr:{ en:{ s:"I'm gonna go to the station.",    jp:"駅に行くつもり。" } } },
  // 接続詞
  { wordId:"or",       exprId:"e_do_you", hl:"or",        tr:{ en:{ s:"Do you want water or food?",      jp:"水か食べ物、どっち？" } } },
  { wordId:"so",       exprId:"e_am",     hl:"so",        tr:{ en:{ s:"I'm tired, so I wanna sleep.",    jp:"疲れたから寝たい。" } } },
  { wordId:"but",      exprId:"e_like",   hl:"but",       tr:{ en:{ s:"I like it, but it's expensive.",  jp:"好きだけど高い。" } } },
  { wordId:"and",      exprId:"e_like",   hl:"and",       tr:{ en:{ s:"I like food and music.",          jp:"食べ物と音楽が好き。" } } },
  // 疑問詞
  { wordId:"what",     exprId:"e_do_you", hl:"What",      tr:{ en:{ s:"What do you eat?",                jp:"何を食べる？" } } },
  { wordId:"when",     exprId:"e_qwhen",  hl:"When",      tr:{ en:{ s:"When do you start?",              jp:"いつ始める？" } } },
  { wordId:"where",    exprId:"e_where",  hl:"Where",     tr:{ en:{ s:"Where do you live?",              jp:"どこに住んでる？" } } },
  { wordId:"how",      exprId:"e_how",    hl:"How",       tr:{ en:{ s:"How do you go to work?",          jp:"どうやって仕事に行く？" } } },
  { wordId:"how_much", exprId:"e_is",     hl:"How much",  tr:{ en:{ s:"How much is this?",               jp:"これいくら？" } } },
  { wordId:"how_long", exprId:"e_do_you", hl:"How long",  tr:{ en:{ s:"How long do you work?",           jp:"どのくらい働く？" } } },
  { wordId:"why",      exprId:"e_do_you", hl:"Why",       tr:{ en:{ s:"Why do you study English?",       jp:"なぜ英語を勉強するの？" } } },
  { wordId:"who",      exprId:"e_is",     hl:"Who",       tr:{ en:{ s:"Who is that man?",               jp:"あの男性は誰？" } } },
  { wordId:"which",    exprId:"e_do_you", hl:"Which",     tr:{ en:{ s:"Which do you like?",              jp:"どっちが好き？" } } },
  { wordId:"what_time",exprId:"e_do_you", hl:"What time", tr:{ en:{ s:"What time do you wake up?",       jp:"何時に起きる？" } } },
  { wordId:"how_old",  exprId:"e_are_you",hl:"How old",   tr:{ en:{ s:"How old are you?",               jp:"何歳ですか？" } } },
  // 時と場所
  { wordId:"here",     exprId:"e_do",     hl:"here",      tr:{ en:{ s:"I live here.",                   jp:"ここに住んでる。" } } },
  { wordId:"there",    exprId:"e_been",   hl:"there",     tr:{ en:{ s:"I've been there.",               jp:"そこに行ったことがある。" } } },
  { wordId:"today",    exprId:"e_am",     hl:"today",     tr:{ en:{ s:"I'm busy today.",                jp:"今日は忙しい。" } } },
  { wordId:"tomorrow", exprId:"e_gonna",  hl:"tomorrow",  tr:{ en:{ s:"I'm gonna go tomorrow.",          jp:"明日行くつもり。" } } },
  { wordId:"yesterday",exprId:"e_did",    hl:"yesterday", tr:{ en:{ s:"I met a friend yesterday.",       jp:"昨日友達に会った。" } } },
  { wordId:"day",      exprId:"e_do",     hl:"day",       tr:{ en:{ s:"I work every day.",              jp:"毎日働く。" } } },
  { wordId:"week",     exprId:"e_gonna",  hl:"week",      tr:{ en:{ s:"I'm gonna travel next week.",     jp:"来週旅行するつもり。" } } },
  { wordId:"month",    exprId:"e_did",    hl:"month",     tr:{ en:{ s:"I started this month.",           jp:"今月始めた。" } } },
  { wordId:"year",     exprId:"e_am",     hl:"year",      tr:{ en:{ s:"I'm busy this year.",            jp:"今年は忙しい。" } } },
  { wordId:"now",      exprId:"e_wanna",  hl:"now",       tr:{ en:{ s:"I wanna sleep now.",             jp:"今すぐ寝たい。" } } },
  // 数字
  { wordId:"one",      exprId:"e_have",   hl:"one",       tr:{ en:{ s:"I have one brother.",             jp:"兄弟が1人いる。" } } },
  { wordId:"two",      exprId:"e_have",   hl:"two",       tr:{ en:{ s:"I have two friends.",             jp:"友達が2人いる。" } } },
  { wordId:"three",    exprId:"e_have",   hl:"three",     tr:{ en:{ s:"I have three cars.",              jp:"車が3台ある。" } } },
  // 返答・相づち（表現タグなし）
  { wordId:"yes",      exprId:"phrase",   hl:"Yes",       tr:{ en:{ s:"Yes, I can.",                     jp:"はい、できます。" } } },
  { wordId:"awesome",  exprId:"phrase",   hl:"awesome",   tr:{ en:{ s:"That's awesome!",                jp:"すごい！" } } },
  { wordId:"really",   exprId:"phrase",   hl:"Really",    tr:{ en:{ s:"Really? That's cool.",           jp:"そうなの？いいね。" } } },
  { wordId:"no",       exprId:"phrase",   hl:"No",        tr:{ en:{ s:"No, I don't.",                   jp:"いいえ、しません。" } } },
  { wordId:"too_bad",  exprId:"phrase",   hl:"too bad",   tr:{ en:{ s:"That's too bad.",                jp:"残念だね。" } } },
  { wordId:"i_see",    exprId:"phrase",   hl:"I see",     tr:{ en:{ s:"I see, that makes sense.",        jp:"なるほど、わかった。" } } },
  // あいさつ（表現タグなし）
  { wordId:"g_morning",exprId:"phrase",   hl:"Good morning", tr:{ en:{ s:"Good morning!",              jp:"おはよう。" } } },
  { wordId:"hi",       exprId:"phrase",   hl:"Hi",        tr:{ en:{ s:"Hi, how are you?",              jp:"やあ、元気？" } } },
  { wordId:"g_evening",exprId:"phrase",   hl:"Good evening", tr:{ en:{ s:"Good evening!",              jp:"こんばんは。" } } },
  { wordId:"bye",      exprId:"phrase",   hl:"Bye",       tr:{ en:{ s:"Bye, see you later.",            jp:"じゃあね、また後で。" } } },
  { wordId:"excuse_me",exprId:"phrase",   hl:"Excuse me", tr:{ en:{ s:"Excuse me, can you help me?",     jp:"すみません、手伝ってくれる？" } } },
  { wordId:"thanks",   exprId:"phrase",   hl:"Thanks",    tr:{ en:{ s:"Thanks a lot!",                  jp:"どうもありがとう。" } } },
  { wordId:"sorry",    exprId:"phrase",   hl:"Sorry",     tr:{ en:{ s:"Sorry, I'm late.",               jp:"ごめん、遅れた。" } } },
  { wordId:"how_are_you",exprId:"phrase", hl:"How are you", tr:{ en:{ s:"How are you today?",           jp:"今日は元気？" } } },
  { wordId:"nice_meet",exprId:"phrase",   hl:"Nice to meet you", tr:{ en:{ s:"Nice to meet you.",       jp:"はじめまして。" } } },
  // その他
  { wordId:"be",       exprId:"e_wanna",  hl:"be",        tr:{ en:{ s:"I wanna be a student.",           jp:"学生になりたい。" } } },
  { wordId:"japan",    exprId:"e_been",   hl:"Japan",     tr:{ en:{ s:"I've been to Japan.",             jp:"日本に行ったことがある。" } } },
  { wordId:"lang",     exprId:"e_ing",    hl:"English",   tr:{ en:{ s:"I'm learning English.",           jp:"英語を勉強している。" } } },
  { wordId:"a_lot",    exprId:"e_have",   hl:"a lot",     tr:{ en:{ s:"I have a lot of friends.",        jp:"友達がたくさんいる。" } } },
  { wordId:"every",    exprId:"e_do",     hl:"every",     tr:{ en:{ s:"I study every day.",             jp:"毎日勉強する。" } } },
  { wordId:"first",    exprId:"e_is",     hl:"first",     tr:{ en:{ s:"This is my first time.",          jp:"これが初めて。" } } },
  { wordId:"last",     exprId:"e_did",    hl:"last",      tr:{ en:{ s:"I saw him last week.",            jp:"先週彼に会った。" } } },
  { wordId:"next",     exprId:"e_gonna",  hl:"next",      tr:{ en:{ s:"I'm gonna start next month.",     jp:"来月始めるつもり。" } } }
];

/* 対応言語の定義（表示名 と TTSの言語コード） */
window.LANGS = {
  en: { label:"英語", voiceLang:"en-US" }
  // 追加例: ko:{ label:"韓国語", voiceLang:"ko-KR" }, zh:{ label:"中国語", voiceLang:"zh-CN" }
};
